### ISSUE TITLE
Make logs more metrics friendly

### ISSUE THREAD

**Issue by nickjer** [OSC/mod_ood_proxy#12]
Should add parse-able metrics to the logs using Splunk formatting as a guide:

http://dev.splunk.com/view/logging/SP-CAAAFCK

**Comment by ericfranz** [comment]
Related: https://github.com/OSC/ood_appkit/issues/10

I'd like to see a common logging formatter configured in NGINX itself to provide most of the information that currently is provided by the custom log formatter in Rails. That way all Passenger apps that log anything will be in the proper format, at least prior to the data they add at the end.

I'd also like to see the access logs switch to splunk format as well. Just have it all be that way.

**Comment by ericfranz** [comment]
http://nginx.org/en/docs/http/ngx_http_log_module.html

**Comment by nickjer** [comment]
This issue is more for the Apache proxy where we currently gather metrics for Google Analytics.
