### ISSUE TITLE
Every time I load a new app for the first time my PUN is reloaded without warning, restarting running shell app instances

### ISSUE THREAD

**Issue by ericfranz** [OSC/mod_ood_proxy#7]
Up to this point we have ignored this as an annoyance for developers, but since we are about to open  development up to everybody soon, we should address this.

Solutions to address this could include:

1. Show the user a warning page when accessing `/nginx/init`. For example, `/nginx/init?redir=/pun/my/app` could display a warning page if the user has any running apps that we know could be negatively affected, with a "continue anyways and reload my PUN" button that sends it to `/nginx/init?redir=/pun/my/app&force=true` where force query param ignores the warning.
2. New app configs loading in "additional" PUN instance(s) so any existing shell (or app instances) are not restarted. Would require design and experiments and possibly modification to both proxy and nginx_stage.
3. ???

**Comment by basilgohar** [comment]
@ericfranz I did not know about this issue, thanks for bringing it up in Slack.  Ideally, choice number 2 above sounds the nicest, so I'd be willing to let you guys spend a couple hours exploring this to determine complexity involved.  Let me know if you think you'd need more than that.

**Comment by ericfranz** [comment]
In fact, instead of `nginx/init?redir=/pun/my/app` displaying a warning page, it might make more sense for the PUN config to be modified so that instead of redirecting to `nginx/init?redir=/pun/my/app` it displays a page with a link to `nginx/init?redir=/pun/my/app` and explains that this will restart the PUN.

That said, I think that `nginx/init` is written in lua, so its easy to add logic and display HTML instead of doing a redirect, versus the PUN serving custom HTML.

**Comment by nickjer** [comment]
This is handled by `nginx_stage` now.
